# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "centos6.6"

  # Fixes changes from https://github.com/mitchellh/vagrant/pull/4707
  config.ssh.insert_key = false

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.

  # CentOS 6.5 x86_64
  config.vm.box_url = "http://cloud.terry.im/vagrant/oraclelinux-6-x86_64.box"

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", 3072] # RAM allocated to each VM
  end

  config.vm.provision :shell, :path => "bootstrap.sh"

  config.vm.define :c6601 do |c6601|
    # uncomment the line below to set up the ambari dev environment
    # c6601.vm.provision :shell, :path => "dev-bootstrap.sh"
    c6601.vm.hostname = "c6601.ambari.apache.org"
    c6601.vm.network :private_network, ip: "192.168.66.101"
  end

  config.vm.define :c6602 do |c6602|
    c6602.vm.hostname = "c6602.ambari.apache.org"
    c6602.vm.network :private_network, ip: "192.168.66.102"
  end

  config.vm.define :c6603 do |c6603|
    c6603.vm.hostname = "c6603.ambari.apache.org"
    c6603.vm.network :private_network, ip: "192.168.66.103"
  end

  config.vm.define :c6604 do |c6604|
    c6604.vm.hostname = "c6604.ambari.apache.org"
    c6604.vm.network :private_network, ip: "192.168.66.104"
  end

  config.vm.define :c6605 do |c6605|
    c6605.vm.hostname = "c6605.ambari.apache.org"
    c6605.vm.network :private_network, ip: "192.168.66.105"
  end

  config.vm.define :c6606 do |c6606|
    c6606.vm.hostname = "c6606.ambari.apache.org"
    c6606.vm.network :private_network, ip: "192.168.66.106"
  end

  config.vm.define :c6607 do |c6607|
    c6607.vm.hostname = "c6607.ambari.apache.org"
    c6607.vm.network :private_network, ip: "192.168.66.107"
  end

  config.vm.define :c6608 do |c6608|
    c6608.vm.hostname = "c6608.ambari.apache.org"
    c6608.vm.network :private_network, ip: "192.168.66.108"
  end

  config.vm.define :c6609 do |c6609|
    c6609.vm.hostname = "c6609.ambari.apache.org"
    c6609.vm.network :private_network, ip: "192.168.66.109"
  end

  config.vm.define :c6610 do |c6610|
    c6610.vm.hostname = "c6610.ambari.apache.org"
    c6610.vm.network :private_network, ip: "192.168.66.110"
  end













  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # config.vm.network :forwarded_port, guest: 80, host: 8080

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network :private_network, ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network :public_network

  # If true, then any SSH connections made will enable agent forwarding.
  # Default value: false
  # config.ssh.forward_agent = true

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider :virtualbox do |vb|
  #   # Don't boot with headless mode
  #   vb.gui = true
  #
  #   # Use VBoxManage to customize the VM. For example to change memory:
  #   vb.customize ["modifyvm", :id, "--memory", "1024"]
  # end
  #
  # View the documentation for the provider you're using for more
  # information on available options.

  # Enable provisioning with Puppet stand alone.  Puppet manifests
  # are contained in a directory path relative to this Vagrantfile.
  # You will need to create the manifests directory and a manifest in
  # the file precise32.pp in the manifests_path directory.
  #
  # An example Puppet manifest to provision the message of the day:
  #
  # # group { "puppet":
  # #   ensure => "present",
  # # }
  # #
  # # File { owner => 0, group => 0, mode => 0644 }
  # #
  # # file { '/etc/motd':
  # #   content => "Welcome to your Vagrant-built virtual machine!
  # #               Managed by Puppet.\n"
  # # }
  #
  # config.vm.provision :puppet do |puppet|
  #   puppet.manifests_path = "manifests"
  #   puppet.manifest_file  = "init.pp"
  # end

  # Enable provisioning with chef solo, specifying a cookbooks path, roles
  # path, and data_bags path (all relative to this Vagrantfile), and adding
  # some recipes and/or roles.
  #
  # config.vm.provision :chef_solo do |chef|
  #   chef.cookbooks_path = "../my-recipes/cookbooks"
  #   chef.roles_path = "../my-recipes/roles"
  #   chef.data_bags_path = "../my-recipes/data_bags"
  #   chef.add_recipe "mysql"
  #   chef.add_role "web"
  #
  #   # You may also specify custom JSON attributes:
  #   chef.json = { :mysql_password => "foo" }
  # end

  # Enable provisioning with chef server, specifying the chef server URL,
  # and the path to the validation key (relative to this Vagrantfile).
  #
  # The Opscode Platform uses HTTPS. Substitute your organization for
  # ORGNAME in the URL and validation key.
  #
  # If you have your own Chef Server, use the appropriate URL, which may be
  # HTTP instead of HTTPS depending on your configuration. Also change the
  # validation key to validation.pem.
  #
  # config.vm.provision :chef_client do |chef|
  #   chef.chef_server_url = "https://api.opscode.com/organizations/ORGNAME"
  #   chef.validation_key_path = "ORGNAME-validator.pem"
  # end
  #
  # If you're using the Opscode platform, your validator client is
  # ORGNAME-validator, replacing ORGNAME with your organization name.
  #
  # If you have your own Chef Server, the default validation client name is
  # chef-validator, unless you changed the configuration.
  #
  #   chef.validation_client_name = "ORGNAME-validator"
end
