# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "centos5.8"

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.

  # CentOS 5.8 x86_64 minimal + guest additions, puppet, chef  
  config.vm.box_url = "http://tag1consulting.com/files/centos-5.8-x86-64-minimal.box"

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", 2048] # RAM allocated to each VM
  end

  config.vm.provision :shell, :path => "bootstrap.sh"

  config.vm.define :c5801 do |c5801|
    c5801.vm.hostname = "c5801.ambari.apache.org"
    c5801.vm.network :private_network, ip: "192.168.58.101"
  end

  config.vm.define :c5802 do |c5802|
    c5802.vm.hostname = "c5802.ambari.apache.org"
    c5802.vm.network :private_network, ip: "192.168.58.102"
  end

  config.vm.define :c5803 do |c5803|
    c5803.vm.hostname = "c5803.ambari.apache.org"
    c5803.vm.network :private_network, ip: "192.168.58.103"
  end

  config.vm.define :c5804 do |c5804|
    c5804.vm.hostname = "c5804.ambari.apache.org"
    c5804.vm.network :private_network, ip: "192.168.58.104"
  end

  config.vm.define :c5805 do |c5805|
    c5805.vm.hostname = "c5805.ambari.apache.org"
    c5805.vm.network :private_network, ip: "192.168.58.105"
  end

  config.vm.define :c5806 do |c5806|
    c5806.vm.hostname = "c5806.ambari.apache.org"
    c5806.vm.network :private_network, ip: "192.168.58.106"
  end

  config.vm.define :c5807 do |c5807|
    c5807.vm.hostname = "c5807.ambari.apache.org"
    c5807.vm.network :private_network, ip: "192.168.58.107"
  end

  config.vm.define :c5808 do |c5808|
    c5808.vm.hostname = "c5808.ambari.apache.org"
    c5808.vm.network :private_network, ip: "192.168.58.108"
  end

  config.vm.define :c5809 do |c5809|
    c5809.vm.hostname = "c5809.ambari.apache.org"
    c5809.vm.network :private_network, ip: "192.168.58.109"
  end

  config.vm.define :c5810 do |c5810|
    c5810.vm.hostname = "c5810.ambari.apache.org"
    c5810.vm.network :private_network, ip: "192.168.58.110"
  end













  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # config.vm.network :forwarded_port, guest: 80, host: 8080

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network :private_network, ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network :public_network

  # If true, then any SSH connections made will enable agent forwarding.
  # Default value: false
  # config.ssh.forward_agent = true

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider :virtualbox do |vb|
  #   # Don't boot with headless mode
  #   vb.gui = true
  #
  #   # Use VBoxManage to customize the VM. For example to change memory:
  #   vb.customize ["modifyvm", :id, "--memory", "1024"]
  # end
  #
  # View the documentation for the provider you're using for more
  # information on available options.

  # Enable provisioning with Puppet stand alone.  Puppet manifests
  # are contained in a directory path relative to this Vagrantfile.
  # You will need to create the manifests directory and a manifest in
  # the file precise32.pp in the manifests_path directory.
  #
  # An example Puppet manifest to provision the message of the day:
  #
  # # group { "puppet":
  # #   ensure => "present",
  # # }
  # #
  # # File { owner => 0, group => 0, mode => 0644 }
  # #
  # # file { '/etc/motd':
  # #   content => "Welcome to your Vagrant-built virtual machine!
  # #               Managed by Puppet.\n"
  # # }
  #
  # config.vm.provision :puppet do |puppet|
  #   puppet.manifests_path = "manifests"
  #   puppet.manifest_file  = "init.pp"
  # end

  # Enable provisioning with chef solo, specifying a cookbooks path, roles
  # path, and data_bags path (all relative to this Vagrantfile), and adding
  # some recipes and/or roles.
  #
  # config.vm.provision :chef_solo do |chef|
  #   chef.cookbooks_path = "../my-recipes/cookbooks"
  #   chef.roles_path = "../my-recipes/roles"
  #   chef.data_bags_path = "../my-recipes/data_bags"
  #   chef.add_recipe "mysql"
  #   chef.add_role "web"
  #
  #   # You may also specify custom JSON attributes:
  #   chef.json = { :mysql_password => "foo" }
  # end

  # Enable provisioning with chef server, specifying the chef server URL,
  # and the path to the validation key (relative to this Vagrantfile).
  #
  # The Opscode Platform uses HTTPS. Substitute your organization for
  # ORGNAME in the URL and validation key.
  #
  # If you have your own Chef Server, use the appropriate URL, which may be
  # HTTP instead of HTTPS depending on your configuration. Also change the
  # validation key to validation.pem.
  #
  # config.vm.provision :chef_client do |chef|
  #   chef.chef_server_url = "https://api.opscode.com/organizations/ORGNAME"
  #   chef.validation_key_path = "ORGNAME-validator.pem"
  # end
  #
  # If you're using the Opscode platform, your validator client is
  # ORGNAME-validator, replacing ORGNAME with your organization name.
  #
  # If you have your own Chef Server, the default validation client name is
  # chef-validator, unless you changed the configuration.
  #
  #   chef.validation_client_name = "ORGNAME-validator"
end
